#!/bin/bash

number='^[0-9]+$'
function focus_if_window {
    if [[ $1 =~ $number ]] ; then
        xdotool windowactivate --sync $1
        exit 0
    fi
}

# Fetch window ids from current desktop
window_ids=($(bspc wm -d | jshon -e focusHistory -a -e nodeId |  grep -vx 0 | tac | awk '!seen[$0]++'))
size=${#window_ids[@]}
if [[ $size -eq 0 ]]; then
    exit 0
fi

# Build window list options
options=""
for (( i=0; i<$size; i++ )); do
    id=${window_ids[$i]}

    if [[ $id -eq 0 ]]; then
	    continue
    fi
    name=$(xdotool getwindowname $id 2> /dev/null)
    class=$(xprop -id $id 2> /dev/null| grep WM_CLASS | awk -F " " '{print $4}'  )
    class="${class%\"}"
    class="${class#\"}"

    # Cap class name to 16 characters 
    class=$(echo "$class" | cut -c 1-16)
    class="$(printf '%-16s' $class)"
    if [[ -n "$name" ]]; then
         options+="$class  $name\n"
    fi
done
options=${options%\\n}

# Focus selected window
result=$(echo -e "$options" | rofi -dmenu -i -format i -p "window:")
focus_if_window "${window_ids[$result]}"
