#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom &
pgrep -x dunst > /dev/null || dunst &
killall alttab
( pgrep -x alttab > /dev/null ) || (sleep 15 && alttab -w 1 -mk Alt_L -d 1 &)
( pgrep -x alttab > /dev/null ) || (sleep 15 && alttab -w 1 -mk Super_L -d 1 &)
xset r rate 300 25
xwallpaper --stretch ~/.config/wp/vsadnica-gory-zamok-reka.jpg
xsetroot -cursor_name left_ptr
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        2
bspc config window_gap          0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus       true
bspc config top_padding 0
bspc config left_padding 0

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Nm-connection-editor state=floating
bspc rule -a zoom desktop='^10'  follow=on
bspc rule -a TeamViewer desktop='^10'
bspc rule -a Google-chrome desktop='^1' follow=on
bspc rule -a Pavucontrol state=floating center=on rectangle=1000x800+0+0
$HOME/.config/polybar/launch.sh
